### ISSUE TITLE
Possible bug with CheckCompatibilityCommand on v2.3.1

### ISSUE THREAD

**Issue by mgermain** [Ericmas001/BluffinMuffin.Protocol#32]
In previous version using:`

```
proto.lobby.CheckCompatibilityCommand({"ImplementedProtocolVersion": proto.__version__}).encode()
```

Would output to following format:

```
'{"CommandName": "CheckCompatibilityCommand", "ImplementedProtocolVersion": "2.2.0"}'
```

But now with 2.3.1 it outputs:

```
'{"CommandName": "CheckCompatibilityCommand", "ImplementedProtocolVersion": {"ImplementedProtocolVersion": "2.3.1"}}'
```

The fact the the version is not a string anymore but a json render this command useless because it is now incompatible with olser version of the protocol.

Also it feels weird to repeat "ImplementedProtocolVersion" for no reason.

**Comment by Ericmas001** [comment]
since 2,3,1 in python using 

```
proto.lobby.CheckCompatibilityCommand({"ImplementedProtocolVersion": proto.__version__}).encode()
```

is wrong. Constructor as changed.

You should simply use

```
proto.lobby.CheckCompatibilityCommand(proto.__version__).encode()
```
